### ISSUE TITLE
Use the HP_groups with colmap

### ISSUE THREAD

**Issue by 11111iuaaa** [TanBinh93/Structure-from-Motion-based-on-Dense-Optical-Flow-method#3]
Hi,
I'd like to use the HP_groups with colmap to reconstruct the dataset you have provided. But as the colmap tutorial said, it needs the descriptor of the features. I can find the descriptor in the HP_groups. Could you tell me more about how to use it or another way to reconstruct it with the HP_groups instead of colmap?
Best Regards!

**Comment by TanBinh93** [comment]
Hello,

Thank you for your interest.
The output of an HP group is a set of matches points (2D points) between images.
You can take a quick look at the form of the HP group in:
https://www.mathworks.com/help/vision/ref/pointtrack.html
 (the HP-group is written according to the structure of point track in Matlab)

You can use the HP- group to reconstruct the 3D model by using Matlab Structure from Motion library as below:
https://www.mathworks.com/help/vision/ug/structure-from-motion.html
https://www.mathworks.com/help/vision/ug/structure-from-motion-from-multiple-views.html

I hope you can find it useful.
Best,
Binh

**Comment by 11111iuaaa** [comment]
Hi,
Thank you very much for your suggestion.
From 
https://www.mathworks.com/help/vision/ug/structure-from-motion-from-multiple-views.html
when using the triangulateMultiview function, it needs the parameter 'intrinsics'. 
I can't find the para in the code you provided. So I try to use the Camera Calibrator to get the intrinsic as the link does. But the  Camera Calibrator can't work out with the images in the dataset. 
Maybe is there another way to ger the intrinsic or I can reconstruct the 3D model without the intrinsic?
Best regards!

**Comment by TanBinh93** [comment]
The intrinsic parameters include the optical center (the principal point), focal length. You can see the intrinsic matrix form in the link below:
https://www.mathworks.com/help/vision/ref/cameraparameters.html

Three popular ways to calculate the intrinsic parameters:
1) These values can be found by the calibration of your camera used to acquire the 2D images for the 3D reconstruction.
https://www.mathworks.com/help/vision/ug/camera-calibration.html
You have to prepare a checkboard to calibrate your camera:
https://www.mathworks.com/help/vision/ug/using-the-single-camera-calibrator-app.html

2) Self-calibration or auto-calibration
 Self-calibration (or auto-calibration) methods are employed in situations where cameras cannot be calibrated using calibration patterns. Self-calibration methods determine the intrinsic camera parameters directly with the content of the images acquired for the 3D scene reconstruction.
https://en.wikipedia.org/wiki/Camera_auto-calibration

3) Exif tags. An alternative to pattern-based calibration methods and self-calibration approaches is to read the camera Exif (exchangeable image file format) tags used to initialize some intrinsic parameters.
https://exiftool.org/TagNames/EXIF.html
COLMAP software uses this approach.

I think you can use COLMAP software to get the intrinsic value of your set of images.

A very good link that includes the 3D reconstruction documents (paper and code) you can refer to:
https://github.com/openMVG/awesome_3DReconstruction_list

Best regards,
Binh

**Comment by TanBinh93** [comment]
You can look at some python programs, you can find some ways to estimate the intrinsic camera parameters. For example:
https://github.com/muneebaadil/how-to-sfm

**Comment by 11111iuaaa** [comment]
Hi!
Thank you very much for your suggestion. Actually, I am trying to use the dataset you provided in google drive. I try to get the result of '191_images_Gastroscopy'. My purpose is to get the reconstruction scene like the video shows. 
It's running for more than 20 hours and it seems it still has to take a lot of time. I will try the method you mentioned later. I wonder if it is normal to take such a long time? 
And thank you again for answering my question! It helps me a lot.

**Comment by TanBinh93** [comment]
Hi,
Yes, it takes a lot of time.
It was my work over 2 years ago.
I know my former colleagues, they have developed the GPU version of this code to make it run faster.
However, I don't have a GPU version
I am sorry about that.

**Comment by 11111iuaaa** [comment]
Hi,
I decided to find other projects to test it. And thank you again for answering my question.
Best regards.
